version: '3.9'

networks:
  nginx-debugger:

services:
  backend:
    image: golang:1.21
    volumes:
      - "./:/src"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: "/src/backend"
    command: go run cmd/main.go
    ports:
      - "9000:9000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
